version: '3.9'

services:

  mongo:
    container_name: nest-mongo
    image: mongo:jammy
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - data-nest:/data/db

  mongo-express:
    container_name: mongoex
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  backend: 
    container_name: nest-backend 
    build: 
      context: . 
      dockerfile: Dockerfile 
    ports: 
      - 3000:3000 
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - NODE_ENV=production

volumes:
  data-nest:
